Web/Controllers/KaryawanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MMI.Common;
using KaryawanORM.LookUp;
using KaryawanORM;
using System.IO;
using Common;
using Microsoft.Reporting.WebForms;
using System.Text.RegularExpressions;
using Syncfusion.Pdf;
using Syncfusion.Pdf.Graphics;
using System.Drawing;
using System.Net.Configuration;
using System.Configuration;
using System.Net.Mail;
using System.Net;

namespace Inventory.Web.Controllers
{
    [Authorize]
    public class KaryawanController : Controller
    {
        //
        // GET: /Karyawan/

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult SendMail()
        {
            NotificationMessage result = new NotificationMessage();
            try
            {
                string textBody = "<table border=" + 1 + " cellpadding=" + 0 + " cellspacing=" + 0 + " width = " + 400 + "><tr bgcolor='#4da6ff'><td><b>KODE</b></td> <td> <b>NAMA </b> </td><td> <b>ALAMAT </b> </td><td> <b>TELP. </b> </td></tr>";
                

                List<MstKaryawan>lstKaryawans = MasterKaryawan.GetAllKaryawans();
                if (lstKaryawans != null && lstKaryawans.Count() > 0)
                {
                    foreach (var item in lstKaryawans)
                    {
                        textBody += "<tr><td>" + item.KaryawanKode + "</td><td>" + item.KaryawanNama + "</td><td>" + item.KaryawanAlamat + "</td><td>" + item.KaryawanTelp + "</td></tr>";
                    }
                }
                textBody += "</table>";
                MailMessage message = new MailMessage();
                SmtpClient smtp = new SmtpClient();
                message.From = new MailAddress("riskie.kalimuda@gmail.com");
                message.To.Add(new MailAddress("mr.cell09@gmail.com"));
                message.Subject = "Daftar Karyawan";
                message.IsBodyHtml = true; //to make message body as html  
                message.Body = "Berikut ini adalah daftar nama-nama karyawan yang diambil dari sisteim" + Environment.NewLine+
                    textBody;
                smtp.Port = 587;
                smtp.Host = "smtp.gmail.com"; //for gmail host  
                smtp.UseDefaultCredentials = false;
                smtp.Credentials = new NetworkCredential("riskie.kalimuda@gmail.com", "marthaak0309258046");
                smtp.EnableSsl = true;
                smtp.DeliveryMethod = SmtpDeliveryMethod.Network;
                smtp.Send(message);
                result = NotificationMessage.Compose(Constants.ACTION_SUCCEEDED_TITLE, String.Format("Kirim email berhasil", "Send Mail"), EnumNotificationMessageType.ALERT_SUCCESS);
            }
            catch (Exception ex)
            {
                result = NotificationMessage.Compose(Constants.ACTION_FAILED_TITLE, String.Format("Kirim email gagal", "Send Mail"), EnumNotificationMessageType.ALERT_FAILED);
            }
            return this.Json(result);
        }

        [HttpPost]
        public ActionResult List()
        {
            DataTablesPostParam param = DataTablesPostParam.ExtractRequestParams(Request.Params);
            DataTablesRecordWrapper<MasterKaryawanGrid> result = new DataTablesRecordWrapper<MasterKaryawanGrid>();
            result = MasterKaryawan.GridSearchEntity(param);
            return new JsonResult { Data = result };
        }

        [HttpGet]
        public void ExportPDF()
        {
            //Create an instance of PdfDocument.
            PdfDocument document = new PdfDocument();
                //Add a page to the document
                PdfPage page = document.Pages.Add();

                //Create PDF graphics for the page
                PdfGraphics graphics = page.Graphics;

                //Set the standard font
                PdfFont font = new PdfStandardFont(PdfFontFamily.Helvetica, 20);

                //Draw the text
                graphics.DrawString("Hello World!!!", font, PdfBrushes.Black, new PointF(0, 0));

                // Open the document in browser after saving it
                document.Save("Output.pdf", HttpContext.ApplicationInstance.Response, HttpReadType.Save);
            }


        [HttpPost]
        public ActionResult GenerateDaftarToPdf()
        {
            List<ExportPdfLookUp> lstExportResult = null;
            lstExportResult = MasterKaryawan.GenerateExportPdf();
          
            if(lstExportResult == null)
                lstExportResult = new List<ExportPdfLookUp>();

                LocalReport localReport = new LocalReport();
                string path = Path.Combine(Server.MapPath("~/Rdlc"), "Exportpdf.rdlc");
                if (System.IO.File.Exists(path))
                {
                    localReport.ReportPath = path;
                }
                else
                {
                    return null;
                }

                ReportDataSource ds = new ReportDataSource("dsExportPdf", lstExportResult);
                localReport.DataSources.Add(ds);

                String mimeType;
                String encoding;
                String fileNameExtension;

                ReportPageSettings setting = localReport.GetDefaultPageSettings();


                string deviceInfo =

                "<DeviceInfo>" +
                "  <OutputFormat>PDF</OutputFormat>" +
                "  <PageWidth>" + setting.PaperSize.Width + "in</PageWidth>" +
                "  <PageHeight>" + setting.PaperSize.Height + "in</PageHeight>" +
                "  <MarginTop>" + setting.Margins.Top + "in</MarginTop>" +
                "  <MarginLeft>" + setting.Margins.Left + "in</MarginLeft>" +
                "  <MarginRight>" + setting.Margins.Right + "in</MarginRight>" +
                "  <MarginBottom>" + setting.Margins.Bottom + "in</MarginBottom>" +
                "</DeviceInfo>";

                Warning[] warnings;
                String[] streams;
                Byte[] renderedBytes;

                renderedBytes = localReport.Render(
                    "PDF",
                    deviceInfo,
                    out mimeType,
                    out encoding,
                    out fileNameExtension,
                    out streams,
                    out warnings);


                String data = Convert.ToBase64String(renderedBytes);
                return Json(data);
        }

        [HttpPost]
        public ActionResult GenerateDaftarToExcel()
        {
            List<ExportPdfLookUp> lstExportResult = null;
            lstExportResult = MasterKaryawan.GenerateExportPdf();

            if (lstExportResult == null)
                lstExportResult = new List<ExportPdfLookUp>();

            LocalReport localReport = new LocalReport();
            string path = Path.Combine(Server.MapPath("~/Rdlc"), "Exportpdf.rdlc");
            if (System.IO.File.Exists(path))
            {
                localReport.ReportPath = path;
            }
            else
            {
                return null;
            }

            ReportDataSource ds = new ReportDataSource("dsExportPdf", lstExportResult);
            localReport.DataSources.Add(ds);

            String mimeType;
            String encoding;
            String fileNameExtension;

            ReportPageSettings setting = localReport.GetDefaultPageSettings();
            
            string deviceInfo =
            "<DeviceInfo>" +
            "  <SimplePageHeaders>False</SimplePageHeaders>" +
            "</DeviceInfo>";

            Warning[] warnings;
            String[] streams;
            Byte[] renderedBytes;

            renderedBytes = localReport.Render(
                "EXCEL",
                deviceInfo,
                out mimeType,
                out encoding,
                out fileNameExtension,
                out streams,
                out warnings);

            String data = Convert.ToBase64String(renderedBytes);
            return Json(data);
        }

        [HttpPost]
        [ActionName("Delete")]
        public ActionResult Delete(Int64 id)
        {
            NotificationMessage result = new NotificationMessage();

            if (id > 0)
            {
                if (MasterKaryawan.Delete(id) > 0)
                {
                    result = NotificationMessage.Compose(Constants.ACTION_SUCCEEDED_TITLE, String.Format(Constants.DELETE_SUCCEEDED_DESCRIPTION, "Data Karyawan"), EnumNotificationMessageType.ALERT_SUCCESS);
                }
                else
                {
                    result = NotificationMessage.Compose(Constants.ACTION_FAILED_TITLE, String.Format(Constants.DELETE_FAILED_DESCRIPTION, "Data Karyawan"), EnumNotificationMessageType.ALERT_FAILED);
                }

            }
            return this.Json(result);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(LookUpKaryawan karyawan)
        {
            String result = "";
            Boolean cekExtentionFotoResult = true;
            MstKaryawan newKaryawan = new MstKaryawan();
            String formatKode = karyawan.KaryawanKode.ToUpper();

            if (!MasterKaryawan.CekKaryawanByKode(formatKode))
            {
                if (karyawan.KaryawanFoto != null)
                {
                    String fileName = Guid.NewGuid().ToString() + karyawan.KaryawanFoto.FileName;
                    String frmtExt = System.IO.Path.GetExtension(fileName);
                    if (MasterKaryawan.CekFormatExtensiFoto(frmtExt))
                    {
                        String uploadFolder = Server.MapPath("~/Uploads/ID/");
                        Boolean isDestPathExist = Directory.Exists(uploadFolder);

                        if (!isDestPathExist)
                            Directory.CreateDirectory(uploadFolder);

Web/Views/Karyawan/Create.cshtml
@{
    ViewBag.Title = "Input Data Baru";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@model KaryawanORM.LookUp.LookUpKaryawan

<div id="main" role="main">
    <div id="ribbon">
        <span class="ribbon-button-alignment"></span>
        <!-- breadcrumb -->
        <ol class="breadcrumb">
            <li>Data 
            </li>
            <li>Tambah
            </li>
        </ol>
    </div>
    <!-- end of ribbon-->
    <div id="content">
        <!-- alert notification -->
        @if (ViewBag.NotificationMessage != null)
        {
            <div class="alert alert-block @ViewBag.NotificationMessage.Type">
                <a class="close" data-dismiss="alert" href="#">×</a>
                <h4 class="alert-heading"><i class="fa fa-check-square-o"></i>@ViewBag.NotificationMessage.Title</h4>
                <p>
                    @ViewBag.NotificationMessage.Description
                </p>
            </div>
        }
        <!-- end of notification -->
        <section id="widget-grid" class="">
            <div class="row">
                <article class="col-sm-12 col-md-12 col-lg-6">
                    <div class="jarviswidget" id="jvItemCategory" data-widget-editbutton="false" data-widget-custombutton="false">
                        <header>
                            <span class="widget-icon"><i class="fa fa-edit"></i></span>
                            <h2>Tambah Data</h2>
                        </header>

                        <!-- widget div-->
                        <div>
                            <!-- widget edit box -->
                            <div class="jarviswidget-editbox">
                                <!-- This area used as dropdown edit box -->
                            </div>
                            <!-- end widget edit box -->

                            <!-- widget content -->
                            <div class="widget-body no-padding">
                                @using (Html.BeginForm("Create", "Karyawan", FormMethod.Post, new { @class = "smart-form", novalidate = "novalidate", id = "formNewKaryawan" }))
                                {
                                    @Html.AntiForgeryToken()
                                    <header>
                                        Tambah Data Karyawan
                                    </header>
                                    <fieldset>
                                        <div class="row">
                                            <section class="col col-6">
                                                @Html.LabelFor(m=>m.KaryawanKode)
                                                <label class="input">
                                                    @Html.TextBoxFor(m => m.KaryawanKode)
                                                </label>
                                            </section>
                                            <section class="col col-6">
                                                @Html.LabelFor(m=>m.KaryawanNama)
                                                <label class="input">
                                                    @Html.TextBoxFor(m => m.KaryawanNama)
                                                </label>
                                            </section>
                                              <section class="col col-6">
                                                @Html.LabelFor(m=>m.KaryawanAlamat)
                                                <label class="input">
                                                    @Html.TextBoxFor(m => m.KaryawanAlamat)
                                                </label>
                                            </section>
                                             <section class="col col-6">
                                                @Html.LabelFor(m=>m.KaryawanTelp)
                                                <label class="input">
                                                    @Html.TextBoxFor(m => m.KaryawanTelp, new { @type = "number" })
                                                </label>
                                            </section>
                                            <fieldset>
                                            <legend>Lampiran Foto</legend>
                                            <div class="row">
                                                <section class="col col-6">
                                                    <label>
                                                        @Html.LabelFor(m => m.KaryawanFoto) :
                                                    </label>
                                                    <label class="input">
                                                        <input type="file" id="KaryawanFoto" name="KaryawanFoto" />
                                                    </label>
                                                </section>
                                            </div>
                                        </fieldset>

                                    </fieldset>
                                   
                                    <footer>
                                        <input id="btnSave" value="Save" type="submit" class="btn btn-primary"/>
                                        <button onclick="btnclose_clicked();" id="btnClose" style="float: left;" type="button" class="btn btn-primary ladda-button" data-color="red">
                                            Close
                                        </button>
                                    </footer>
                                }
                            </div>
                            <!-- end widget content -->
                        </div>
                        <!-- end widget div -->
                    </div>
                    <!-- end widget -->
                </article>
            </div>
        </section>
    </div>
</div>
@section scripts {

    <script type="text/javascript">
        $(document).ready(function () {
            pageSetUp();

            var $newCompanyForm = $('#formNewKaryawan').validate({
                rules: {
                    KaryawanKode: {
                        required: true
                    },
                    KaryawanNama: {
                        required: true
                    },
                    KaryawanAlamat: {
                        required: true,
                    },
                    KaryawanTelp: {
                        required: true
                    }
                },
                messages: {
                    KaryawanKode: {
                        required: 'Kode harus diisi'
                    },
                    KaryawanNama: {
                        required: 'Nama harus diisi'
                    },
                    KaryawanAlamat: {
                        required: 'Alamat harus diisi',
                    }
                },
                submitHandler: function (form) {
                    btn_Save(form);
                    return false;
                }
            });
        });
        function btn_Save(form) {
            var $form = $(form);
            var formData = new FormData($form[0]);
            $.ajax({
                url: '/Karyawan/Create/',
                type: "POST",
                cache: false,
                data: formData,
                contentType: false,
                processData: false,
                success: function (msg) {
                    if (msg != null) {
                        $.SmartMessageBox({
                            title: msg,
                            buttons: '[OK]'
                        }, function (ButtonPressed) {
                            //Do nothing
                        });
                    }
                },
                error: function (err) {
                    console.log(err);
                }
            });
        }

        function btnclose_clicked() {
            window.location = "/";
        };
    </script>

}

Web/Views/Karyawan/Edit.cshtml
@{
    ViewBag.Title = "Edit Data";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@model KaryawanORM.LookUp.LookUpKaryawan

<div id="main" role="main">
    <div id="ribbon">
        <span class="ribbon-button-alignment"></span>
        <!-- breadcrumb -->
        <ol class="breadcrumb">
            <li>Data 
            </li>
            <li>Edit
            </li>
        </ol>
    </div>
    <!-- end of ribbon-->
    <div id="content">
        <!-- alert notification -->
      <div id="notificationPlace" style="display: none;"></div>
        <!-- end of notification -->
        <section id="widget-grid" class="">
            <div class="row">
                <article class="col-sm-12 col-md-12 col-lg-6">
                    <div class="jarviswidget" id="jvItemCategory" data-widget-editbutton="false" data-widget-custombutton="false">
                        <header>
                            <span class="widget-icon"><i class="fa fa-edit"></i></span>
                            <h2>Edit Data</h2>
                        </header>

                        <!-- widget div-->
                        <div>
                            <!-- widget edit box -->
                            <div class="jarviswidget-editbox">
                                <!-- This area used as dropdown edit box -->
                            </div>
                            <!-- end widget edit box -->

                            <!-- widget content -->
                            <div class="widget-body no-padding">
                                @using (Html.BeginForm("Edit", "Karyawan", FormMethod.Post, new { @class = "smart-form", novalidate = "novalidate", id = "formEditKaryawan" }))
                                {
                                    @Html.AntiForgeryToken()
                                    <header>
                                        Edit Karyawan Form
                                    </header>
                                    <fieldset>
                                        <div class="row">
                                            @Html.HiddenFor(m=>m.KaryawanID)
                                            @Html.HiddenFor(m=>m.KaryawanFotoFileName)
                                            <section class="col col-6">
                                                @Html.LabelFor(m=>m.KaryawanKode)
                                                <label class="input">
                                                    @Html.TextBoxFor(m => m.KaryawanKode)
                                                </label>
                                            </section>
                                            <section class="col col-6">
                                                @Html.LabelFor(m=>m.KaryawanNama)
                                                <label class="input">
                                                    @Html.TextBoxFor(m => m.KaryawanNama)
                                                </label>
                                            </section>
                                              <section class="col col-6">
                                                @Html.LabelFor(m=>m.KaryawanAlamat)
                                                <label class="input">
                                                    @Html.TextBoxFor(m => m.KaryawanAlamat)
                                                </label>
                                            </section>
                                             <section class="col col-6">
                                                @Html.LabelFor(m=>m.KaryawanTelp)
                                                <label class="input">
                                                    @Html.TextBoxFor(m => m.KaryawanTelp, new { @type = "number" })
                                                </label>
                                            </section>
                                            <fieldset>
                                            <legend>Foto Saat Ini</legend>
                                                 <div class="row">
                                                <section class="col col-6">
                                                    <img src="@Html.DisplayTextFor(m => m.KaryawanFotoFileName)" width="50">
                                                </section>
                                            </div>
                                            <div class="row">
                                                <section class="col col-6">
                                                    <label>
                                                        <b>Untuk mengganti foto klik tombol dibawah.</b>
                                                        <label class="input">
                                                        <input type="file" id="KaryawanFoto" name="KaryawanFoto" />
                                                    </label>
                                                    </label>
                                                </section>
                                            </div>
                                        </fieldset>

                                    </fieldset>
                                   
                                    <footer>
                                        <input id="btnSave" value="Save" type="submit" class="btn btn-primary"/>
                                        <button onclick="btnclose_clicked();" id="btnClose" style="float: left;" type="button" class="btn btn-primary ladda-button" data-color="red">
                                            Close
                                        </button>
                                    </footer>
                                }
                            </div>
                            <!-- end widget content -->
                        </div>
                        <!-- end widget div -->
                    </div>
                    <!-- end widget -->
                </article>
            </div>
        </section>
    </div>
</div>
@section scripts {

    <script type="text/javascript">
        $(document).ready(function () {
            pageSetUp();

            var $newCompanyForm = $('#formEditKaryawan').validate({
                rules: {
                    KaryawanKode: {
                        required: true
                    },
                    KaryawanNama: {
                        required: true
                    },
                    KaryawanAlamat: {
                        required: true,
                    },
                    KaryawanTelp: {
                        required: true
                    }
                },
                messages: {
                    KaryawanKode: {
                        required: 'Kode harus diisi'
                    },
                    KaryawanNama: {
                        required: 'Nama harus diisi'
                    },
                    KaryawanAlamat: {
                        required: 'Alamat harus diisi',
                    }
                },
                submitHandler: function (form) {
                    btn_Save(form);
                    return false;
                }
            });
        });
        function btn_Save(form) {
            var $form = $(form);
            var formData = new FormData($form[0]);
            $.ajax({
                url: $form.attr("action"),
                type: "POST",
                cache: false,
                data: formData,
                contentType: false,
                processData: false,
                success: function (result) {
                    if (result != null) {
                        $('#notificationPlace').show();
                        showAlertMessage(notificationPlace, result.ResultMessage.Title, result.ResultMessage.Description, result.ResultMessage.Type);
                    }
                },
                error: function (err) {
                    console.log(err);
                }
            });
        }

        function btnclose_clicked() {
            window.location = "/";
        };
    </script>

}