Web/Controllers/AuthenticateController.cs
using KaryawanORM;
using KaryawanORM.LookUp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using System.Web.UI;

namespace Inventory.Web.Controllers
{
    public class AuthenticateController : Controller
    {
        //
        // GET: /Authenticate/

        public ActionResult Index()
        {
            return View();
        }

        [OutputCache(Location = OutputCacheLocation.None)]
        public ActionResult Login(String returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(ParamLogin paramLogin, String returnUrl)
        {
            if (ModelState.IsValid)
            {
                if (paramLogin != null)
                {
                    if (MasterUser.IsUserHaveLogin(paramLogin.Username, paramLogin.Password))
                    {
                        FormsAuthentication.SetAuthCookie(paramLogin.Username, false);
                    }
                    return RedirectToHomePage(returnUrl);
                }
            }
            return View(paramLogin);
        }

        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Karyawan");
        }

        private ActionResult RedirectToHomePage(String returnUrl)
        {
            String decodedUrl = Server.UrlDecode(returnUrl);
            if (Url.IsLocalUrl(returnUrl))
                return Redirect(returnUrl);
            else
                return RedirectToAction("Index", "Karyawan");
        }
    }
}

Web/Views/Authenticate/Login.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en-us">
<head>
    <meta charset="utf-8" />

    <meta name="viewport" content="width=device-width, initial-state=1.0, maximum-scale=1.0, user-scalable=no" />
    
    <title>@ViewBag.Title</title>

    @Styles.Render("~/css/site")

	<link rel="stylesheet" type="text/css" media="screen" href="/css/bootstrap.min.css">	
	<link rel="stylesheet" type="text/css" media="screen" href="/css/font-awesome.min.css">
	<link rel="stylesheet" type="text/css" media="screen" href="/css/smartadmin-production.css">
	<link rel="stylesheet" type="text/css" media="screen" href="/css/smartadmin-skins.css">

    @*<link rel="shortcut icon" href="/img/favicon/favicon.ico" type="image/x-icon" />
    <link rel="icon" href="/img/favicon/favicon.ico" type="image/x-icon" />*@

    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,300,400,700">

</head>
<body id="login" class="animated fadeInDown">
		<header id="header">
			<div id="logo-group">
				<span id="logo"> <img src="" alt="SmartAdmin"> </span>
			</div>
			<span id="login-header-space"></span>
		</header>

		<div id="main" role="main">

			<!-- MAIN CONTENT -->
			<div id="content" class="container">

				<div class="row">
					<div class="col-xs-12 col-sm-12 col-md-7 col-lg-8 hidden-xs hidden-sm">
						<h1 class="txt-color-red login-header-big">Sistem Manajemen Karyawan</h1>
						@*<div class="hero">*@

							@*<div class="pull-left login-desc-box-l">
								<h4 class="paragraph-header">Selamat Datang, di Mondelez Rapid Tracking Claim!</h4>
                                <h4 class="paragraph-header">Jika ada pertanyaan, silahkan menghubungi <b>claim-id@mdlz.com</b></h4>
							</div>*@
							
							@*<img src="/img/demo/sample.jpg" class="pull-right display-image" alt="" style="width:210px">*@

						@*</div>*@
					</div>
					<div class="col-xs-12 col-sm-12 col-md-5 col-lg-4">
						<div class="well no-padding">
                            @using (Html.BeginForm("Login", "Authenticate", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "smart-form client-form", id = "loginForm" }))
                            {
                                @Html.AntiForgeryToken()
								<header>
									Silahkan Login
								</header>
								<fieldset>
									<section>
										<label class="label">User Name</label>
										<label class="input"> <i class="icon-append fa fa-user"></i>
											<input name="Username">
											<b class="tooltip tooltip-top-right"><i class="fa fa-user txt-color-teal"></i> Silahkan masukkan user name Anda</b></label>
									</section>

									<section>
										<label class="label">Password</label>
										<label class="input"> <i class="icon-append fa fa-lock"></i>
											<input type="password" name="Password">
											<b class="tooltip tooltip-top-right"><i class="fa fa-lock txt-color-teal"></i> Masukkan kata kunci Anda</b> </label>
									</section>

									@*<section>
										<label class="checkbox">
											<input type="checkbox" name="remember" checked="false">
											<i></i>Ingat Saya</label>
									</section>*@
								</fieldset>
								<footer>
									<button type="submit" class="btn btn-primary">
										Login
									</button>
								</footer>
                            }
						</div>
					</div>
				</div>
			</div>

		</div>

	    <script src="/js/libs/jquery-2.0.2.min.js"></script>
		<script src="/js/libs/jquery-ui-1.10.3.min.js"></script>
		<script src="/js/bootstrap/bootstrap.min.js"></script>
		<script src="/js/notification/SmartNotification.min.js"></script>
		<script src="/js/smartwidgets/jarvis.widget.min.js"></script>
		<script src="/js/plugin/easy-pie-chart/jquery.easy-pie-chart.min.js"></script>
		<script src="/js/plugin/sparkline/jquery.sparkline.min.js"></script>
		<script src="/js/plugin/jquery-validate/jquery.validate.min.js"></script>
		<script src="/js/plugin/masked-input/jquery.maskedinput.min.js"></script>
		<script src="/js/plugin/select2/select2.min.js"></script>
		<script src="/js/plugin/bootstrap-slider/bootstrap-slider.min.js"></script>
		<script src="/js/plugin/msie-fix/jquery.mb.browser.min.js"></script>
		<script src="/js/plugin/smartclick/smartclick.js"></script>
		<!--[if IE 7]>
			<h1>Your browser is out of date, please update your browser by going to www.microsoft.com/download</h1>
		<![endif]-->

		<!-- MAIN APP JS FILE -->
		<script src="/js/app.js"></script>

		<script type="text/javascript">
		    runAllForms();

		    $(function () {
		        // Validation
		        $("#login-form").validate({
		            // Rules for form validation
		            rules: {
		                email: {
		                    required: true,
		                },
		                password: {
		                    required: true,
		                    minlength: 3,
		                    maxlength: 20
		                }
		            },

		            // Messages for form validation
		            messages: {
		                email: {
		                    required: 'Silahkan isi user name Anda.',
		                },
		                password: {
		                    required: 'Silahkan masukkan kata kunci Anda'
		                }
		            },

		            // Do not change code below
		            errorPlacement: function (error, element) {
		                error.insertAfter(element.parent());
		            }
		        });
		    });
		</script>
</body>
</html>